# Generated by Django 4.1.2 on 2022-10-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categorías',
                'db_table': 'Categoría',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categpría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Productos',
                'db_table': 'Producto',
                'ordering': ['id'],
            },
        ),
    ]
